spring:
  application:
    name: swbothook
logging:
  level:
    com.blindbugs.swbot.application.controller.HookController: DEBUG
    com.blindbugs.swbot.application.controller: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
